services:
  postgres-db:
    image: postgres:15-alpine
    container_name: maestria-postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-admin}
      POSTGRES_DB: maestria_users
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: maestria-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  user-service:
    build:
      context: ../maestria-user-service
    container_name: maestria-user-service
    depends_on:
      - postgres-db
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_NAME=maestria_users
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - APP_JWT_SECRET=${APP_JWT_SECRET}

  api-gateway:
    build:
      context: ../maestria-api-gateway
    container_name: maestria-api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service

  course-service:
    build:
      context: ../maestria-course-service
    container_name: maestria-course-service
    depends_on:
      - postgres-db
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_NAME=maestria_courses
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - spring.security.oauth2.resourceserver.jwt.secret-key=${APP_JWT_SECRET}

volumes:
  postgres-data: